// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSfQ9d8UAJuRrIe10fC__EiolTwkZNbUQ',
    appId: '1:528356564197:web:550e6236978018e1ad880c',
    messagingSenderId: '528356564197',
    projectId: 'todoapp-f3dd4',
    authDomain: 'todoapp-f3dd4.firebaseapp.com',
    storageBucket: 'todoapp-f3dd4.firebasestorage.app',
    measurementId: 'G-Y77ZTCGDDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQEoevSFKQgOvqpJLZ8GaKpbS7HjA298',
    appId: '1:528356564197:android:7ae185a16c88b6e0ad880c',
    messagingSenderId: '528356564197',
    projectId: 'todoapp-f3dd4',
    storageBucket: 'todoapp-f3dd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3qf3w79prdlm2CC2NJGnuWJjaJnhBT4',
    appId: '1:528356564197:ios:65cd7cec39e5aaa6ad880c',
    messagingSenderId: '528356564197',
    projectId: 'todoapp-f3dd4',
    storageBucket: 'todoapp-f3dd4.firebasestorage.app',
    iosBundleId: 'com.example.todoappPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf3qf3w79prdlm2CC2NJGnuWJjaJnhBT4',
    appId: '1:528356564197:ios:65cd7cec39e5aaa6ad880c',
    messagingSenderId: '528356564197',
    projectId: 'todoapp-f3dd4',
    storageBucket: 'todoapp-f3dd4.firebasestorage.app',
    iosBundleId: 'com.example.todoappPro',
  );
}
